# Generated by Django 2.2 on 2019-04-10 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_auto_20190409_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Clicked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clickAt', models.DateField(auto_now=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shortener.Link')),
            ],
        ),
    ]
