# Generated by Django 2.2 on 2019-04-10 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0006_auto_20190410_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='timeCreated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
